name: publish koba
# This workflow publishes koba on crates.io.
permissions:
  contents: read
on:
  push:
    tags:
      - v*
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
env:
  CARGO_TERM_COLOR: always
jobs:
  check-publish:
    name: Publish koba on crates.io
    env:
      KOBA_TOKEN: ${{ secrets.KOBA_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""

      - name: Check koba
        run: cargo publish -p koba --dry-run

      - name: Publish koba
        run: cargo publish -p koba --token $KOBA_TOKEN
